# -*- coding: utf-8 -*-
"""kiến tập

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m9LbRfSUWgPzHbFa0hG_LmcZDApIAGXh
"""

!pip install -q seaborn
!pip install scikit-learn-extra

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from mpl_toolkits.mplot3d import Axes3D

df = pd.read_csv("/content/digital_wallet_transactions.csv")  # Đổi đường dẫn nếu chạy local
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

print("🔹 Kích thước dữ liệu gốc:", df.shape)
print("🔹 Các cột trong dữ liệu:", list(df.columns))

df_cleaned = df.drop(columns=['idx', 'transaction_id', 'merchant_id'])

numeric_cols = ['product_amount', 'transaction_fee', 'cashback', 'loyalty_points']
Q1 = df_cleaned[numeric_cols].quantile(0.25)
Q3 = df_cleaned[numeric_cols].quantile(0.75)
IQR = Q3 - Q1
outlier_mask = ((df_cleaned[numeric_cols] < (Q1 - 1.5 * IQR)) |
                (df_cleaned[numeric_cols] > (Q3 + 1.5 * IQR))).any(axis=1)
df_filtered = df_cleaned[~outlier_mask]

print("🔹 Số lượng giao dịch bị loại bỏ:", outlier_mask.sum())
print("🔹 Kích thước sau khi loại outlier:", df_filtered.shape)

snapshot_date = df_filtered['transaction_date'].max() + pd.Timedelta(days=1)
rfm = df_filtered.groupby('user_id').agg({
    'transaction_date': lambda x: (snapshot_date - x.max()).days,
    'user_id': 'count',
    'product_amount': 'sum'
}).rename(columns={
    'transaction_date': 'Recency',
    'user_id': 'Frequency',
    'product_amount': 'Monetary'
}).reset_index()

print("🔹 Kích thước bảng RFM:", rfm.shape)
print(rfm.head())

scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm[['Recency', 'Frequency', 'Monetary']])

# 6. Phân cụm bằng KMeans
print("\n🔹 Áp dụng phân cụm KMeans (k=4)...")
kmeans = KMeans(n_clusters=4, random_state=42)
rfm['Cluster'] = kmeans.fit_predict(rfm_scaled)

print("🔹 Gắn nhãn cụm thành công. Xem vài dòng đầu:")
print(rfm.head())

print("\n🔹 Hiển thị biểu đồ phân cụm 3D:")
def plot_3d_rfm(data, title):
    fig = plt.figure(figsize=(8,6))
    ax = fig.add_subplot(111, projection='3d')
    ax.scatter(data['Recency'], data['Frequency'], data['Monetary'],
               c=data['Cluster'], cmap='viridis')
    ax.set_xlabel('Recency')
    ax.set_ylabel('Frequency')
    ax.set_zlabel('Monetary')
    ax.set_title(title)
    plt.show()

plot_3d_rfm(rfm, "Customer Segmentation using RFM and KMeans")

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

# Tính SSE với K từ 1 đến 10
sse = {}
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(rfm_scaled)
    sse[k] = kmeans.inertia_

# Vẽ biểu đồ Elbow bằng matplotlib đơn giản
plt.figure(figsize=(8, 5))
plt.plot(list(sse.keys()), list(sse.values()), marker='o')
plt.title('Phương pháp Elbow ')
plt.xlabel('Số cụm (k)')
plt.ylabel('SSE (Tổng bình phương sai số trong cụm)')
plt.xticks(range(1, 11))
plt.grid(True)
plt.show()

# 1. Tóm tắt RFM trung bình theo cụm
rfm_cluster_summary = rfm.groupby('Cluster').agg({
    'Recency': 'mean',
    'Frequency': 'mean',
    'Monetary': 'mean'
}).round(2)

print("📊 Trung bình RFM theo từng cụm:")
print(rfm_cluster_summary)

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

# Dữ liệu đã chuẩn hóa
rfm_scaled_df = pd.DataFrame(rfm_scaled, columns=['Recency', 'Frequency', 'Monetary'])

fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111, projection='3d')

# Vẽ scatter với nhãn cụm làm màu
scatter = ax.scatter(
    rfm_scaled_df['Recency'],
    rfm_scaled_df['Frequency'],
    rfm_scaled_df['Monetary'],
    c=rfm['Cluster'],
    cmap='viridis',
    s=50
)

# Thiết lập nhãn trục
ax.set_xlabel('Recency')
ax.set_ylabel('Frequency')
ax.set_zlabel('Monetary')

# Thêm chú thích
legend = ax.legend(*scatter.legend_elements(), title='Cluster')
ax.add_artist(legend)

plt.title('Clusters of Customers (3D)')
plt.show()

import pandas as pd

# Đọc dữ liệu từ file CSV ví dụ:
df = pd.read_csv('/content/digital_wallet_transactions.csv')  # hoặc đường dẫn của bạn

# Chuyển đổi kiểu ngày
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

snapshot_date = df['transaction_date'].max() + pd.Timedelta(days=1)

rfm = df.groupby('user_id').agg({
    'transaction_date': lambda x: (snapshot_date - x.max()).days,
    'user_id': 'count',
    'product_amount': 'sum'
}).rename(columns={
    'transaction_date': 'Recency',
    'user_id': 'Frequency',
    'product_amount': 'Monetary'
}).reset_index()

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

# Chuẩn hóa dữ liệu
scaler = StandardScaler()
rfm_normalized = scaler.fit_transform(rfm[['Recency', 'Frequency', 'Monetary']])

# KMeans phân cụm
kmeans = KMeans(n_clusters=4, random_state=42)
rfm['Cluster'] = kmeans.fit_predict(rfm_normalized)

# Vẽ biểu đồ 3D
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

scatter = ax.scatter(
    rfm_normalized[:, 0],
    rfm_normalized[:, 1],
    rfm_normalized[:, 2],
    c=rfm['Cluster'],
    cmap='viridis',
    s=50
)

ax.set_xlabel('Recency (normalized)')
ax.set_ylabel('Frequency (normalized)')
ax.set_zlabel('Monetary (normalized)')
plt.legend(*scatter.legend_elements(), title='Cluster')
plt.title("3D KMeans Clustering of RFM Scores")
plt.show()

import pandas as pd

# Giả sử bạn đã load file thành công với:
# df = pd.read_csv('...')

# Chuyển cột ngày về đúng định dạng
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Tạo snapshot date
snapshot_date = df['transaction_date'].max() + pd.Timedelta(days=1)

# Tính bảng RFM
rfm = df.groupby('user_id').agg({
    'transaction_date': lambda x: (snapshot_date - x.max()).days,
    'user_id': 'count',
    'product_amount': 'sum'
}).rename(columns={
    'transaction_date': 'Recency',
    'user_id': 'Frequency',
    'product_amount': 'Monetary'
}).reset_index()

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Đọc dữ liệu CSV từ file bạn cung cấp
df = pd.read_csv('digital_wallet_transactions.csv')  # ⚠️ Đổi path nếu cần
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Tạo bảng RFM
snapshot_date = df['transaction_date'].max() + pd.Timedelta(days=1)
customer = df.groupby('user_id').agg({
    'transaction_date': lambda x: (snapshot_date - x.max()).days,
    'user_id': 'count',
    'product_amount': 'sum'
}).rename(columns={
    'transaction_date': 'Recency',
    'user_id': 'Frequency',
    'product_amount': 'Monetary'
}).reset_index()

# Chuẩn hóa dữ liệu
scaler = StandardScaler()
rfm_normalized = scaler.fit_transform(customer[['Recency', 'Frequency', 'Monetary']])

# K-Medoids clustering
customer['Cluster'] = KMeans(n_clusters=5, random_state=0).fit_predict(rfm_normalized)

# Plotting in 3D
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')
colors = ['r', 'g', 'b', 'y', 'c']

for i in range(5):
    points = rfm_normalized[customer['Cluster'] == i]
    ax.scatter(points[:, 0], points[:, 1], points[:, 2],
               s=50, c=colors[i], label=f'Cluster {i}')

ax.set_title('3D K-Medoids Clustering of RFM Scores')
ax.set_xlabel('Recency (normalized)')
ax.set_ylabel('Frequency (normalized)')
ax.set_zlabel('Monetary (normalized)')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from mpl_toolkits.mplot3d import Axes3D

# Chuẩn hóa dữ liệu đầu vào (nếu cần)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
rfm_normalized = scaler.fit_transform(customer[['Recency', 'Frequency', 'Monetary']])

# Ánh xạ lại DataFrame chuẩn hóa
customer_scaled = pd.DataFrame(rfm_normalized, columns=['Recency', 'Frequency', 'Monetary'])

# Áp dụng KMeans++
kmeans_model = KMeans(n_clusters=5, init='k-means++', random_state=0)
customer_scaled['Cluster'] = kmeans_model.fit_predict(customer_scaled)

# Vẽ biểu đồ 3D
fig = plt.figure(figsize=(10, 9))
ax = fig.add_subplot(111, projection='3d')
scatter = ax.scatter(
    customer_scaled['Recency'],
    customer_scaled['Frequency'],
    customer_scaled['Monetary'],
    c=customer_scaled['Cluster'],
    cmap='viridis',
    s=40
)

ax.set_title('3D KMeans++ Clustering of RFM Scores')
ax.set_xlabel('Recency (normalized)')
ax.set_ylabel('Frequency (normalized)')
ax.set_zlabel('Monetary (normalized)')

# Thêm chú thích
legend1 = ax.legend(*scatter.legend_elements(), title="Clusters")
ax.add_artist(legend1)

plt.show()

print(customer.describe())

#calculation of the RFM score
customer["RecencyScore"] = pd.qcut(customer["Recency"],5,labels=[5,4,3,2,1])

customer["FrequencyScore"] = pd.qcut(customer["Frequency"].rank(method="first"),5,labels=[1,2,3,4,5])

customer["MonetaryScore"] = pd.qcut(customer["Monetary"],5,labels=[1,2,3,4,5])

customer['RFM_SCORE']=customer['RecencyScore'].astype(str)+customer['FrequencyScore'].astype(str)+customer['MonetaryScore'].astype(str)
customer.head(5000)



# Tạo mã phân khúc từ điểm RFM
customer['Segment'] = customer['RecencyScore'].astype(str) + \
                      customer['FrequencyScore'].astype(str) + \
                      customer['MonetaryScore'].astype(str)

# Ánh xạ mã 3 chữ số sang tên gọi phân khúc
seg_map = {
    r'555': 'Champions',
    r'155': "Can't Lose Them",
    r'255': 'At Risk',
    r'111': 'Lost customers',
    r'211': 'About To Sleep',
    r'311': 'Hibernating',
    r'135': 'New Customers',
    r'355': 'Potential Loyalist',
    r'445': 'Loyal Customers',
    r'225': 'Needing Attention',
    # bạn có thể bổ sung thêm tùy dataset
}

# Thay mã phân khúc bằng tên gọi
customer['Segment'] = customer['Segment'].replace(seg_map, regex=True)

rfm_level_agg = customer.groupby('Segment').agg({
    'Recency': 'mean',
    'Frequency': 'mean',
    'Monetary': ['mean', 'count']
}).round(1)

print(rfm_level_agg)

"""Histogram"""

# Vẽ biểu đồ histogram cho giá trị Monetary
plt.figure(figsize=(10, 6))
sns.histplot(customer['Monetary'], bins=50, kde=True, color='skyblue', edgecolor='black')

# Vẽ biểu đồ histogram cho Frequency
plt.figure(figsize=(10, 6))
sns.histplot(customer['Frequency'], bins=30, kde=True, color='skyblue', edgecolor='black')

plt.figure(figsize=(10, 6))
sns.histplot(customer['Recency'], bins=30, kde=True, color='skyblue', edgecolor='black')

import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

# Đọc dữ liệu
df = pd.read_csv('/content/digital_wallet_transactions.csv')

# Chuyển transaction_date sang định dạng datetime
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Tìm ngày giao dịch mới nhất trong dữ liệu
latest_date = df['transaction_date'].max()

# Tính Recency: số ngày từ giao dịch gần nhất của mỗi user đến ngày cuối cùng trong tập dữ liệu
recency_df = df.groupby('user_id')['transaction_date'].max().reset_index()
recency_df['Recency'] = (latest_date - recency_df['transaction_date']).dt.days

# Vẽ biểu đồ boxplot
plt.figure(figsize=(8, 6))
plt.boxplot(recency_df['Recency'], vert=True, patch_artist=True, boxprops=dict(facecolor='cornflowerblue'))
plt.title('Recency')
plt.ylabel('Days')
plt.grid(axis='y')

# Thêm ghi chú như trong luận văn
plt.figtext(0.5, -0.1, 'Figure 4.1: Boxplots of Recency', wrap=True, horizontalalignment='center', fontsize=12)

plt.show()

frequency_df['Frequency'].value_counts().sort_index()

plt.figure(figsize=(8, 6))
plt.boxplot(frequency_df['Frequency'], vert=True, patch_artist=True,
            boxprops=dict(facecolor='cornflowerblue'), showmeans=True)
plt.title('Frequency')
plt.ylabel('Number of Transactions')
plt.grid(axis='y')
plt.figtext(0.5, -0.1, 'Figure 4.2: Boxplots of Frequency', wrap=True, horizontalalignment='center', fontsize=12)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Đọc dữ liệu từ file CSV (đảm bảo bạn đã upload file vào Colab)
df = pd.read_csv('/content/digital_wallet_transactions.csv')

# Tính tổng chi tiêu theo từng khách hàng (Monetary)
monetary_df = df.groupby('user_id')['product_amount'].sum().reset_index()
monetary_df.rename(columns={'product_amount': 'Monetary'}, inplace=True)

# Tính IQR
Q1 = monetary_df['Monetary'].quantile(0.25)
Q3 = monetary_df['Monetary'].quantile(0.75)
IQR = Q3 - Q1

# Lọc dữ liệu không có outliers
filtered_monetary = monetary_df[
    (monetary_df['Monetary'] >= Q1 - 1.5 * IQR) &
    (monetary_df['Monetary'] <= Q3 + 1.5 * IQR)
]

plt.figure(figsize=(8, 6))
plt.boxplot(filtered_monetary['Monetary'], vert=True, patch_artist=True,
            boxprops=dict(facecolor='cornflowerblue'))
plt.title('Monetary')
plt.ylabel('Total Amount Spent')
plt.grid(axis='y')

plt.show()

import pandas as pd
from datetime import datetime

# Đọc dữ liệu
df = pd.read_csv('/content/digital_wallet_transactions.csv')
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Ngày tham chiếu để tính Recency (là ngày mới nhất trong tập dữ liệu)
ref_date = df['transaction_date'].max()

# Recency: số ngày kể từ giao dịch cuối đến ref_date
recency_df = df.groupby('user_id')['transaction_date'].max().reset_index()
recency_df['Recency'] = (ref_date - recency_df['transaction_date']).dt.days

# Frequency: số lượng giao dịch
frequency_df = df.groupby('user_id')['transaction_id'].nunique().reset_index()
frequency_df.rename(columns={'transaction_id': 'Frequency'}, inplace=True)

# Monetary: tổng số tiền đã chi
monetary_df = df.groupby('user_id')['product_amount'].sum().reset_index()
monetary_df.rename(columns={'product_amount': 'Monetary'}, inplace=True)

# Gộp lại thành bảng RFM
rfm = recency_df.merge(frequency_df, on='user_id').merge(monetary_df, on='user_id')

# Tính điểm theo quintiles
rfm['R_Score'] = pd.qcut(rfm['Recency'], 5, labels=[5,4,3,2,1])  # Recency càng thấp càng tốt
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1,2,3,4,5])
rfm['M_Score'] = pd.qcut(rfm['Monetary'].rank(method='first'), 5, labels=[1,2,3,4,5])

# Tính RFM Score theo định dạng R*100 + F*10 + M
rfm['RFM_Score'] = rfm['R_Score'].astype(int) * 100 + \
                   rfm['F_Score'].astype(int) * 10 + \
                   rfm['M_Score'].astype(int)

# Đổi tên cột cho giống bảng
rfm.rename(columns={'user_id': 'CustomerKey'}, inplace=True)

# Hiển thị vài dòng đầu
rfm[['CustomerKey', 'R_Score', 'F_Score', 'M_Score', 'RFM_Score']].head(5000)

plt.figure(figsize=(8, 5))
plt.boxplot(
    df['product_amount'],
    vert=True,
    patch_artist=True,
    flierprops=dict(marker='o', color='black', markersize=5),
    boxprops=dict(facecolor='lightblue'),
    medianprops=dict(color='black'),
    whiskerprops=dict(color='black'),
    capprops=dict(color='black')
)
plt.title('product_amount')
plt.ylabel('Amount')
plt.xticks([1], ['1'])
plt.ylim(0, 10000)  # Giới hạn trục y như hình mẫu

plt.grid(axis='y')
plt.show()

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# Đọc dữ liệu
df = pd.read_csv('/content/digital_wallet_transactions.csv')
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Tính RFM
reference_date = df['transaction_date'].max()
rfm = df.groupby('user_id').agg({
    'transaction_date': lambda x: (reference_date - x.max()).days,
    'transaction_id': 'count',
    'product_amount': 'sum'
}).reset_index()

rfm.columns = ['CustomerKey', 'Recency', 'Frequency', 'Monetary']

# Chuẩn hóa dữ liệu RFM
scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm[['Recency', 'Frequency', 'Monetary']])

# Elbow method
wcss = []
K = range(2, 10)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(rfm_scaled)
    wcss.append(kmeans.inertia_)

# Vẽ biểu đồ Elbow
plt.figure(figsize=(10, 5))
plt.plot(K, wcss, 'bx-')
plt.xlabel('k')
plt.ylabel('Distortion')
plt.title('The Elbow Method Showing the Optimal k')
plt.show()

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# Đọc dữ liệu
df = pd.read_csv("digital_wallet_transactions.csv")

# Xử lý ngày
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Tính giá trị RFM
reference_date = df['transaction_date'].max()
rfm = df.groupby('user_id').agg({
    'transaction_date': lambda x: (reference_date - x.max()).days,
    'transaction_id': 'count',
    'product_amount': 'sum'
}).reset_index()

rfm.columns = ['CustomerKey', 'Recency', 'Frequency', 'Monetary']

# Chuẩn hóa
scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm[['Recency', 'Frequency', 'Monetary']])

# KMeans
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
rfm['Cluster'] = kmeans.fit_predict(rfm_scaled)

# Vẽ biểu đồ 3D
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')
scatter = ax.scatter(
    rfm['Recency'], rfm['Frequency'], rfm['Monetary'],
    c=rfm['Cluster'], cmap='viridis'
)
ax.set_xlabel('Recency')
ax.set_ylabel('Frequency')
ax.set_zlabel('Monetary')
ax.set_title('Customer Segmentation based on RFM')
legend = ax.legend(*scatter.legend_elements(), title="Clusters")
ax.add_artist(legend)
plt.show()

# Bước 1: Tải thư viện cần thiết
import pandas as pd

# Bước 2: Tải file từ máy lên Colab (nếu cần)
from google.colab import files
uploaded = files.upload()

# Bước 3: Đọc file CSV (đảm bảo tên file đúng)
df = pd.read_csv('digital_wallet_transactions.csv')

# Bước 4: Chuyển đổi định dạng ngày tháng
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Bước 5: Tổng số lượng khách hàng giao dịch
total_unique_customers = df['user_id'].nunique()
print("Tổng số lượng khách hàng giao dịch duy nhất:", total_unique_customers)

# Bước 6: Tạo thêm cột tháng (dạng Period: YYYY-MM)
df['month'] = df['transaction_date'].dt.to_period('M')

# Bước 7: Tính số khách hàng giao dịch theo từng tháng
monthly_customers = df.groupby('month')['user_id'].nunique().reset_index()
monthly_customers.columns = ['Month', 'Unique_Customers']
print("\nSố lượng khách hàng giao dịch theo từng tháng:")
print(monthly_customers)

# Đếm số lượng giao dịch theo từng product category
top_categories = df['product_category'].value_counts().head(10).reset_index()
top_categories.columns = ['Product Category', 'Number of Transactions']

# In bảng top 10
print("Top 10 danh mục sản phẩm có nhiều giao dịch nhất:")
print(top_categories)

# (Tuỳ chọn) Vẽ biểu đồ trực quan
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.barh(top_categories['Product Category'], top_categories['Number of Transactions'], color='skyblue')
plt.gca().invert_yaxis()  # Danh mục nhiều nhất nằm trên cùng
plt.title('Top 10 Product Categories by Number of Transactions')
plt.xlabel('Number of Transactions')
plt.tight_layout()
plt.show()

# Đếm số lượng giao dịch theo merchant
top_merchants = df['merchant_name'].value_counts().head(10).reset_index()
top_merchants.columns = ['Merchant Name', 'Number of Transactions']

# In ra bảng top 10
print("Top 10 merchant có số lượng giao dịch nhiều nhất:")
print(top_merchants)

# (Tuỳ chọn) Vẽ biểu đồ
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.barh(top_merchants['Merchant Name'], top_merchants['Number of Transactions'], color='lightgreen')
plt.gca().invert_yaxis()
plt.title('Top 10 Merchants by Number of Transactions')
plt.xlabel('Number of Transactions')
plt.tight_layout()
plt.show()

# Bước 1: Chuyển đổi cột ngày giao dịch sang định dạng datetime (nếu chưa)
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Bước 2: Tạo cột tháng
df['month'] = df['transaction_date'].dt.to_period('M')

# Bước 3: Tính tổng số tiền cashback theo từng tháng
monthly_cashback = df.groupby('month')['cashback'].sum().reset_index()
monthly_cashback.columns = ['Month', 'Total Cashback']

# Bước 4: Hiển thị bảng kết quả
print("Tổng số tiền cashback theo từng tháng:")
print(monthly_cashback)

# (Tuỳ chọn) Vẽ biểu đồ
import matplotlib.pyplot as plt

monthly_cashback['Month'] = monthly_cashback['Month'].astype(str)
plt.figure(figsize=(12, 6))
plt.plot(monthly_cashback['Month'], monthly_cashback['Total Cashback'], marker='o', color='orange')
plt.title('Tổng số tiền Cashback theo từng tháng')
plt.xlabel('Tháng')
plt.ylabel('Tổng tiền Cashback')
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Đọc dữ liệu nếu cần (nếu đã có sẵn df thì bỏ qua dòng này)
# df = pd.read_csv('digital_wallet_transactions.csv')

# Đếm số lượng giao dịch theo địa điểm
location_counts = df['location'].value_counts()

# Đổi tên địa điểm sang tiếng Việt
location_labels = {
    'Urban': 'Thành thị',
    'Suburban': 'Ngoại ô',
    'Rural': 'Nông thôn'
}
translated_labels = [location_labels.get(loc, loc) for loc in location_counts.index]

# Vẽ biểu đồ hình tròn
plt.figure(figsize=(8, 6))
colors = ['darkblue', 'firebrick', 'mediumturquoise']
plt.pie(location_counts, labels=translated_labels, autopct='%1.2f%%', colors=colors, startangle=90)
plt.title('Tổng số giao dịch theo khu vực', fontsize=14, color='lightblue')
plt.legend(title='Khu vực', labels=translated_labels, loc='center left', bbox_to_anchor=(1, 0.5))
plt.axis('equal')  # Giữ biểu đồ hình tròn tròn đều

# Nền tối như trong ví dụ
plt.style.use('dark_background')

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Đọc dữ liệu nếu cần
# df = pd.read_csv('digital_wallet_transactions.csv')

# Tính tổng chi tiêu theo khu vực
total_spending_by_location = df.groupby('location')['product_amount'].sum()

# Đổi nhãn sang tiếng Việt
location_labels = {
    'Urban': 'Thành thị',
    'Suburban': 'Ngoại ô',
    'Rural': 'Nông thôn'
}
translated_labels = [location_labels.get(loc, loc) for loc in total_spending_by_location.index]

# Vẽ biểu đồ hình tròn
plt.figure(figsize=(8, 6))
colors = ['darkblue', 'firebrick', 'mediumturquoise']
plt.pie(total_spending_by_location, labels=translated_labels, autopct='%1.1f%%', colors=colors, startangle=90)
plt.title('Tổng chi tiêu theo khu vực', fontsize=14, color='lightblue')
plt.legend(title='Khu vực', labels=translated_labels, loc='center left', bbox_to_anchor=(1, 0.5))
plt.axis('equal')  # Giữ hình tròn đều

# Nền tối giống hình mẫu
plt.style.use('dark_background')

plt.tight_layout()
plt.show()